global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["app:3333"]

  - job_name: "localhost"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["localhost:3333"]

